### ISSUE TITLE
Open Beauty Facts

### ISSUE THREAD

**Issue by teolemon** [costajob/inci_score#1]
We're the team of volunteers behind Open Food Facts, and we've started attacking cosmetics. :-)
https://world.openbeautyfacts.org
https://github.com/openfoodfacts

**Comment by costajob** [comment]
That's very interesting! ;)
Regarding the issue: i checked that there was an issue on "levenshtein distance" on empty sources, which i fixed.
Consider the list of ingredients and related hazards are fetched from biodizionario.com where you can find updated data.
Let me know if you will face any further issues and please do specify the stack trace and a brief description.
Best
